### ISSUE TITLE
krr might not be supported on Ubuntu 20.04?

### ISSUE THREAD

**Issue by LarsBingBong** [robusta-dev/krr#145]
**Describe the bug**
krr throwing: `[2459] Error loading Python lib '/home/linuxbrew/.linuxbrew/Cellar/krr/1.6.0/libexec/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /home/linuxbrew/.linuxbrew/Cellar/krr/1.6.0/libexec/libpython3.9.so.1.0)`

**To Reproduce**
Execute `krr --help` on **Ubuntu 20.04**.

**Expected behavior**
`krr --help` to work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 20.04 Ubuntu
 - Pytho

**Additional context**
- Similar issue in another project: https://github.com/khoj-ai/khoj/issues/378
- I installed `krr` via `linuxbrew`.

**Comment by kartoch** [comment]
It seems the problem is not related to krr: the library `libpython3.9.so.1.0` wants to use the library `/lib/x86_64-linux-gnu/libm.so.6` with version `GLIBC_2.35` but it does not seems to be available in your system.

Based on what I read, you're using `homebrew`. I recommend switching to `pyenv` to setup a new virtualenv with a dedicated python (different from the system one), or docker.

**Comment by LeaveMyYard** [comment]
So, [from what I've found](https://askubuntu.com/questions/1408049/how-can-i-get-glibc-2-35-on-ubuntu-20-04) it is possible to update glibc to a newer version, but it seems like it is better not to do it

The best approach for your case would be to refer to [manual installation](https://github.com/robusta-dev/krr#manual-installation) and to install using just python

Also maybe it would work with some other package managers, maybe that will install python, but currently we do not plan to do that, but we would love to merge someone's PR with that
