### ISSUE TITLE
Unable to get history range from VictoriaMetrics

### ISSUE THREAD

**Issue by farioas** [robusta-dev/krr#313]
**Describe the bug**
I'm using `victoria-metrics-k8s-stack` instead of prometheus. So, when I run `krr simple` command I receive a warning that affects recommendations:
```
WARNING  Was not able to get history range for cluster dev-xxx-xxx-cluster. This is not critical, will try continue.                                                                                  runner.py:221
```

**To Reproduce**
1. Install `victoria-metrics-k8s-stack`
2. Run `krr simple`

**Expected behavior**
The history should be discovered from VictoriaMetrics. 

**Are you interested in contributing a fix for this?**
No. But I made some investigation. 
krr currently uses `prometheus_tsdb_head_series` to get the number of active time series, while in VM this metric has another name `vm_cache_entries`.

**Comment by aantn** [comment]
Thank you for reporting and nice find! It would be good to fix this.

Please note that despite the warning you should be able to receive recommendations just fine. We fetch the history to warn you when the cluster is new and there isn't enough data in Prometheus to give recommendations (rather than giving you a whole list of empty recommendations in that case.)

Can you confirm you receive recommendations despite the warning?

**Comment by farioas** [comment]
I confirm that I received recommendations, but in first I considered them as inaccurate. 

Now I figured it out, that I have to append arg `--use-oomkill-data`.

**Comment by aantn** [comment]
Wonderful, thanks for the update.
